apiVersion: v1
kind: ServiceAccount
metadata:
  name: signed-service-account
  namespace: default
secrets:
- name: my-registry-credentials
- name: my-key-pair
imagePullSecrets:
- name: my-registry-credentials