version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 5043:443
    links:
      - registry:registry
    volumes:
      - ./auth:/etc/nginx/conf.d
      - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro
  registry:
    image: registry:2
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5005
    volumes:
      - ./data:/var/lib/registry