# Prometheus config
global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
      monitor: 'prometheus-monitor-docker'
rule_files:
  # - "first.rules"         # No rules for this example
  # - "second.rules"        # No rules for this example
scrape_configs:
  - job_name: 'prometheus'  # Establish reachability to Prometheus system
    static_configs:
      - targets: ['192.168.1.226:9090']
  - job_name: 'docker'      # Connects the target to the dockerd daemon
    static_configs:
      - targets: ['192.168.1.226:9323']
  - job_name: node          # Connects the target on the node exporter
    static_configs:
      - targets: ['192.168.1.226:9100']
  - job_name: cadvisor
    static_configs:         # Connects the target to cAdvisor
      - targets:
          - cadvisor:8080
  - job_name: python          # Connects the target to python endpoint
    static_configs:
      - targets: ['192.168.1.226:9191']