apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devops-team-impersonator
rules:
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
  resourceNames: ["devops-team-admin"]