apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-team-view
  namespace: devops-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
1subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: devops-team