apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-team-admin-impersonate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devops-team-impersonator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: devops-team