apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BlockIngressHostSharingAlternativeNamespace
metadata:
  name: ingress-conflict
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ingress"]
  parameters:
    namespace: ["alt_namespace"]